---
title: "Wrangling Practice and Dates"
---

## Load Packages
```{r}
library(tidyverse)
```


## Load Data

Election Data by County
```{r}
penguins <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv')
head(penguins)
```

## Missing Value in One Column

```{r}
penguins |> 
  is.na()
```



## Missing Values in Each Column
```{r}
penguins |> 
  is.na() |> 
  colSums() |> 
  table()
```

## Missing Values in Each Row
```{r}
penguins |> 
  is.na() |> 
  rowSums() |>
  table()
```


```{r}
penguins |> 
  count(species)
```


```{r}
# Sort Gentoo penguins from biggest to smallest with respect to their 
# bill length in cm (there are 10 mm in a cm)
penguins |> 
  filter(species == "Gentoo") |> 
  mutate(bill_length_cm = bill_length_mm/10) |> 
  arrange(desc(bill_length_cm))
```


```{r}
# Sort the species from smallest to biggest with respect to their 
# average bill length in cm
penguins |> 
  mutate(bill_length_cm = bill_length_mm/10) |> 
  group_by(species) |> 
  summarise(mean = mean(bill_length_cm, na.rm = TRUE)) |> 
  arrange(mean)

```


















